# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ca0bd519039a4553cf304365712d320f06e551be80ce0d2427f3c6552e9715bf18b6c844580907a51c646042179c0a7eb5e7ac20a181f91796b7fd749f56dd

test:
  secret_key_base: 121273a92504513c738dcd0b3523db88bb4624b076f327ed51c60093ddd0e399bb8d254e8e54031f9b836f542643f8d809f8ade4506e69d2bdf46af73a2aaaf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
